name: "Samantha Estrada"
output_dir: "."
navbar:
  title: "Samantha Estrada"
  left:
    - text: "Teaching"
      href: Teaching.html
    - text: "Publications"
      href: pubs.html
  right:
    - icon: fa-github fa-lg
      href: https://github.com/estr2525
    - icon: fa-twitter fa-lg
      href: https://twitter.com/estr2525
output:
    html_document:
    theme: paper

theme: jekyll-theme-minimal